# Generated by Django 5.2.8 on 2025-12-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the profile is visible to other users', verbose_name='public profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='LinkedIn username'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_content',
            field=models.TextField(blank=True, help_text='Markdown content for the user portfolio', verbose_name='portfolio content'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='external portfolio URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='show email on profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline or headline for profile', max_length=200, verbose_name='tagline'),
        ),
    ]
