from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Custom User model for DeadDevelopers platform.
    Extends the standard Django User model to track AI usage and other platform-specific attributes.
    """
    email = models.EmailField(_('email address'), unique=True)
    ai_percentage = models.IntegerField(
        _('AI usage percentage'),
        default=0,
        help_text=_('Percentage of code generated by AI (0-100)')
    )
    bio = models.TextField(_('biography'), blank=True)
    avatar = models.ImageField(
        _('avatar'),
        upload_to='avatars/',
        blank=True,
        null=True
    )
    
    # Social links
    github_username = models.CharField(max_length=50, blank=True)
    twitter_username = models.CharField(max_length=50, blank=True)
    website = models.URLField(max_length=200, blank=True)
    
    # Preferences
    theme_preference = models.CharField(
        max_length=20,
        choices=[('dark', 'Dark'), ('light', 'Light')],
        default='dark'
    )
    
    # Metrics
    challenge_count = models.IntegerField(default=0)
    completed_projects = models.IntegerField(default=0)
    
    # Required for Django-Allauth
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
    
    def __str__(self):
        return self.email
    
    def get_display_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.username
